### ISSUE TITLE
Allow directories to be ignored to prevent import conflicts

### ISSUE THREAD

**Issue by gurs1kh** [PavelDymkov/babel-plugin-auto-import#3]
I originally posted this issue here: https://forums.expo.io/t/babel-config-js-how-do-i-prevent-config-from-conflicting-with-dependencies/19698

Basically, I am trying to use `babel-plugin-auto-import` to auto-import `React`. Here is my `babel.config.js`:
```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      ['auto-import', {
        declarations: [
          { path: 'react', default: 'React',  members: ['Component'] },
          { path: 'react-native', members: ['View', 'Text', 'Platform']},
        ]
      }]
    ],
  };
};
```
But this seems to conflict with an expo dependency:
```
/node_modules/expo/build/effects/BlurView.ios.js: You must pass a scope and parentPath unless traversing a Program/File. Instead of that you tried to traverse a Identifier node without passing scope and parentPath.
```
It appears to conflict with `BlurView.ios.js:2`:
``` import * as React from 'react'; ```

I'm sure there are plenty of other cases where this sort of problem could occur, so perhaps it would be useful to allow for directories to be ignored for this plugin (if possible).

At least, it would be useful to ignore `node_modules` since you'd only really expect a user to want to auto-import into their own project and not any dependencies.

**Comment by gurs1kh** [comment]
I came across another issue where something like this occurred. `Platform` is used in `node_modules/react-native-gesture-handler/touchables/TouchableNativeFeedback.android.js` without an import and I have a custom extend `Platform` module.
Due to this being a problem I could see happening a lot elsewhere, I have gone ahead and implemented a fix (see PR #4)

**Comment by peterp** [comment]
I think this is should be closed?

**Comment by gurs1kh** [comment]
yeah, you're correct.
